version: '2'

volumes:
  orderer.example.com:
  peer0.auditor.example.com:
  peer0.factory.example.com:
  peer0.dealer.example.com:
  peer0.police.example.com:
  peer0.insurance.example.com:

networks:
  net:

services:

  peer-base:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7050
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../fixtures/channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ../fixtures/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ../fixtures/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - net

  peer0.auditor.example.com:
    container_name: peer0.auditor.example.com
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.auditor.example.com
      - CORE_PEER_ADDRESS=peer0.auditor.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.auditor.example.com:7051
      - CORE_PEER_LOCALMSPID=auditor
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
      - ../fixtures/organizations/peerOrganizations/auditor.example.com/peers/peer0.auditor.example.com/msp:/etc/hyperledger/fabric/msp
      - ../fixtures/organizations/peerOrganizations/auditor.example.com/peers/peer0.auditor.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.auditor.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - net

  peer0.factory.example.com:
    container_name: peer0.factory.example.com
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.factory.example.com
      - CORE_PEER_ADDRESS=peer0.factory.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.factory.example.com:8051
      - CORE_PEER_LOCALMSPID=factory
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
      - ../fixtures/organizations/peerOrganizations/factory.example.com/peers/peer0.factory.example.com/msp:/etc/hyperledger/fabric/msp
      - ../fixtures/organizations/peerOrganizations/factory.example.com/peers/peer0.factory.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.factory.example.com:/var/hyperledger/production
    ports:
      - 8051:8051
      - 8053:8053
    networks:
      - net

  peer0.dealer.example.com:
    container_name: peer0.dealer.example.com
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dealer.example.com
      - CORE_PEER_ADDRESS=peer0.dealer.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dealer.example.com:8051
      - CORE_PEER_LOCALMSPID=dealer
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
      - ../fixtures/organizations/peerOrganizations/dealer.example.com/peers/peer0.dealer.example.com/msp:/etc/hyperledger/fabric/msp
      - ../fixtures/organizations/peerOrganizations/dealer.example.com/peers/peer0.dealer.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.dealer.example.com:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9053:9053
    networks:
      - net

  peer0.police.example.com:
    container_name: peer0.police.example.com
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.police.example.com
      - CORE_PEER_ADDRESS=peer0.police.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.police.example.com:10051
      - CORE_PEER_LOCALMSPID=police
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
      - ../fixtures/organizations/peerOrganizations/police.example.com/peers/peer0.police.example.com/msp:/etc/hyperledger/fabric/msp
      - ../fixtures/organizations/peerOrganizations/police.example.com/peers/peer0.police.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.police.example.com:/var/hyperledger/production
    ports:
      - 10051:10051
      - 10053:10053
    networks:
      - net

  peer0.insurance.example.com:
    container_name: peer0.insurance.example.com
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurance.example.com
      - CORE_PEER_ADDRESS=peer0.insurance.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.example.com:10051
      - CORE_PEER_LOCALMSPID=insurance
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
      - ../fixtures/organizations/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/msp:/etc/hyperledger/fabric/msp
      - ../fixtures/organizations/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.insurance.example.com:/var/hyperledger/production
    ports:
      - 11051:11051
      - 11053:11053
    networks:
      - net

  cli.auditor.example.com:
    container_name: cli.auditor.example.com
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli.auditor.example.com
      - CORE_PEER_ADDRESS=peer0.auditor.example.com:7051
      - CORE_PEER_LOCALMSPID=auditor
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/auditor.example.com/peers/peer0.auditor.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/auditor.example.com/peers/peer0.auditor.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/auditor.example.com/peers/peer0.auditor.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/auditor.example.com/users/Admin@auditor.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincode/:/opt/gopath/src/chaincode
      - ../../chaincode/:/opt/gopath/src/github.com/chaincode
      - ../fixtures/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/channel-artifacts
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/fixtures/channel-artifacts
    depends_on:
      - peer0.auditor.example.com
    networks:
      - net

  cli.factory.example.com:
    container_name: cli.factory.example.com
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli.factory.example.com
      - CORE_PEER_ADDRESS=peer0.factory.example.com:8051
      - CORE_PEER_LOCALMSPID=factory
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/factory.example.com/peers/peer0.factory.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/factory.example.com/peers/peer0.factory.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/factory.example.com/peers/peer0.factory.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/factory.example.com/users/Admin@factory.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincode/:/opt/gopath/src/chaincode
      - ../../chaincode/:/opt/gopath/src/github.com/chaincode
      - ../fixtures/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/channel-artifacts
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/fixtures/channel-artifacts
    depends_on:
      - peer0.factory.example.com
    networks:
      - net

  cli.dealer.example.com:
    container_name: cli.dealer.example.com
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli.dealer.example.com
      - CORE_PEER_ADDRESS=peer0.dealer.example.com:9051
      - CORE_PEER_LOCALMSPID=dealer
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/dealer.example.com/peers/peer0.dealer.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/dealer.example.com/peers/peer0.dealer.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/dealer.example.com/peers/peer0.dealer.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/dealer.example.com/users/Admin@dealer.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincode/:/opt/gopath/src/chaincode
      - ../../chaincode/:/opt/gopath/src/github.com/chaincode
      - ../fixtures/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/channel-artifacts
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/fixtures/channel-artifacts
    depends_on:
      - peer0.dealer.example.com
    networks:
      - net

  cli.police.example.com:
    container_name: cli.police.example.com
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli.police.example.com
      - CORE_PEER_ADDRESS=peer0.police.example.com:10051
      - CORE_PEER_LOCALMSPID=police
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/police.example.com/peers/peer0.police.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/police.example.com/peers/peer0.police.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/police.example.com/peers/peer0.police.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/police.example.com/users/Admin@police.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincode/:/opt/gopath/src/chaincode
      - ../../chaincode/:/opt/gopath/src/github.com/chaincode
      - ../fixtures/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/channel-artifacts
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/fixtures/channel-artifacts
    depends_on:
      - peer0.police.example.com
    networks:
      - net

  cli.insurance.example.com:
    container_name: cli.insurance.example.com
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli.insurance.example.com
      - CORE_PEER_ADDRESS=peer0.insurance.example.com:11051
      - CORE_PEER_LOCALMSPID=insurance
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/insurance.example.com/users/Admin@insurance.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincode/:/opt/gopath/src/chaincode
      - ../../chaincode/:/opt/gopath/src/github.com/chaincode
      - ../fixtures/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/channel-artifacts
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/fixtures/channel-artifacts
    depends_on:
      - peer0.insurance.example.com
    networks:
      - net

  cli.orderer.example.com:
    container_name: cli.orderer.example.com
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli.orderer.example.com
      - CORE_PEER_ADDRESS=orderer.example.com:7050
      - CORE_PEER_LOCALMSPID=orderer
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincode/:/opt/gopath/src/chaincode
      - ../../chaincode/:/opt/gopath/src/github.com/chaincode
      - ../fixtures/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/channel-artifacts
    depends_on:
      - orderer.example.com
    networks:
      - net